### PR TITLE
Fix bug when creating lesson on filtered contacts

### LINKED ISSUE #130: Fix bug when creating lesson on filtered contacts

### PR DESCRIPTION
**Pull request by NorbertLoh**
Fixes #130.

### CODE REVIEW

**Review by ethantyh692 — COMMENTED** [review]
LGTM!

File: src/main/java/tutorease/address/logic/commands/AddLessonCommand.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public AddLessonCommand(StudentId studentId, StartDateTime startDateTime, Locati
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
-        ObservableList<Person> personList = model.getTutorEase().getPersonList();
+        ObservableList<Person> personList = model.getFilteredPersonList();
```
Comment (Ma-Xizi) [inline src/main/java/tutorease/address/logic/commands/AddLessonCommand.java:62]: This will work well if we intend to create lessons from a filtered list of contacts, after using the find contact command.

**Review by Chronoxy — APPROVED** [review]
LGTM 👍
